/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pdstore.tela;

import java.sql.*;
import javax.swing.JOptionPane;
import br.com.pdstore.dal.Conexao;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Michel
 */
public class TelaGerenciaEstoque extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    String guarda[] = new String[2];
    
    /**
     * Creates new form TelaGerenciaEstoque
     */
    public TelaGerenciaEstoque() {
        initComponents();
        conexao = Conexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        txtPesquisaUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEstoqueCentral = new javax.swing.JTextField();
        txtAldeia = new javax.swing.JTextField();
        txtVerbo = new javax.swing.JTextField();
        txtAclimacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        slctSoma = new javax.swing.JComboBox<>();
        slctSoma1 = new javax.swing.JComboBox<>();
        slctSoma2 = new javax.swing.JComboBox<>();
        slctSoma3 = new javax.swing.JComboBox<>();
        txtNomeUsuario5 = new javax.swing.JTextField();
        txtResultados = new javax.swing.JTextField();
        txtResultados1 = new javax.swing.JTextField();
        txtResultados2 = new javax.swing.JTextField();
        txtResultados3 = new javax.swing.JTextField();
        btnAdiciona = new javax.swing.JButton();
        txtSoma2 = new javax.swing.JTextField();
        txtSoma4 = new javax.swing.JTextField();
        txtSoma1 = new javax.swing.JTextField();
        txtSoma3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtItaim = new javax.swing.JTextField();
        slctSoma4 = new javax.swing.JComboBox<>();
        txtSoma5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtResultados4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFormattedTextField1.setText("jFormattedTextField1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("=");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerente de Estoques");
        setResizable(false);

        txtPesquisaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaUsuarioActionPerformed(evt);
            }
        });
        txtPesquisaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaUsuarioKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Lupa.png"))); // NOI18N

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaMouseClicked(evt);
            }
        });
        jTabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabela);

        txtDescricao.setEditable(false);
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Estoque Central");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Produto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Verbo Divino");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Aldeia da Serra");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Itaim");

        txtEstoqueCentral.setEditable(false);
        txtEstoqueCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueCentralActionPerformed(evt);
            }
        });
        txtEstoqueCentral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstoqueCentralKeyReleased(evt);
            }
        });

        txtAldeia.setEditable(false);
        txtAldeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAldeiaActionPerformed(evt);
            }
        });

        txtVerbo.setEditable(false);
        txtVerbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerboActionPerformed(evt);
            }
        });

        txtAclimacao.setEditable(false);
        txtAclimacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAclimacaoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quantidade");

        slctSoma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Somar", "Modificar" }));
        slctSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctSomaActionPerformed(evt);
            }
        });

        slctSoma1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Somar", "Modificar" }));
        slctSoma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctSoma1ActionPerformed(evt);
            }
        });

        slctSoma2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Somar", "Modificar" }));
        slctSoma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctSoma2ActionPerformed(evt);
            }
        });

        slctSoma3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Somar", "Modificar" }));
        slctSoma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctSoma3ActionPerformed(evt);
            }
        });

        txtNomeUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuario5ActionPerformed(evt);
            }
        });

        txtResultados.setEditable(false);
        txtResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadosActionPerformed(evt);
            }
        });

        txtResultados1.setEditable(false);
        txtResultados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultados1ActionPerformed(evt);
            }
        });

        txtResultados2.setEditable(false);
        txtResultados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultados2ActionPerformed(evt);
            }
        });

        txtResultados3.setEditable(false);
        txtResultados3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultados3ActionPerformed(evt);
            }
        });

        btnAdiciona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Adiciona_Estoque.png"))); // NOI18N
        btnAdiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaActionPerformed(evt);
            }
        });

        txtSoma2.setText("0");
        txtSoma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoma2ActionPerformed(evt);
            }
        });
        txtSoma2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoma2KeyReleased(evt);
            }
        });

        txtSoma4.setText("0");
        txtSoma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoma4ActionPerformed(evt);
            }
        });
        txtSoma4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoma4KeyReleased(evt);
            }
        });

        txtSoma1.setText("0");
        txtSoma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoma1ActionPerformed(evt);
            }
        });
        txtSoma1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoma1KeyReleased(evt);
            }
        });

        txtSoma3.setText("0");
        txtSoma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoma3ActionPerformed(evt);
            }
        });
        txtSoma3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoma3KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("=");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("=");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("=");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Aclimação");

        txtItaim.setEditable(false);
        txtItaim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItaimActionPerformed(evt);
            }
        });

        slctSoma4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Somar", "Modificar" }));
        slctSoma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctSoma4ActionPerformed(evt);
            }
        });

        txtSoma5.setText("0");
        txtSoma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoma5ActionPerformed(evt);
            }
        });
        txtSoma5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoma5KeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("=");

        txtResultados4.setEditable(false);
        txtResultados4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultados4ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtDescricao))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAclimacao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAldeia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtVerbo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(txtEstoqueCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtItaim, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slctSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slctSoma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slctSoma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slctSoma3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slctSoma4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoma5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoma4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoma1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoma2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoma3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultados4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResultados1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResultados2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResultados3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(btnAdiciona)))
                .addGap(90, 90, 90))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(txtNomeUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(533, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(42, 42, 42)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(txtEstoqueCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(slctSoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(slctSoma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSoma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9)
                                                .addComponent(txtResultados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtVerbo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSoma1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAldeia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(slctSoma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSoma3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(txtResultados2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAclimacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(slctSoma3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSoma4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtResultados3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtItaim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(slctSoma4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSoma5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(txtResultados4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdiciona)
                        .addGap(95, 95, 95))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(404, Short.MAX_VALUE)
                    .addComponent(txtNomeUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(164, 164, 164)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaUsuarioActionPerformed

    private void txtPesquisaUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaUsuarioKeyReleased
        // O evento key realese é responsável pela tabela se atualizar em tempo real
        pesquisar_cliente();
    }//GEN-LAST:event_txtPesquisaUsuarioKeyReleased

    private void jTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaMouseClicked
        setar_campos();
    }//GEN-LAST:event_jTabelaMouseClicked

    private void jTabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaKeyPressed

    }//GEN-LAST:event_jTabelaKeyPressed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtEstoqueCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueCentralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueCentralActionPerformed

    private void txtAldeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAldeiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAldeiaActionPerformed

    private void txtVerboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerboActionPerformed

    private void txtAclimacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAclimacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAclimacaoActionPerformed

    private void slctSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctSomaActionPerformed
        if (slctSoma.getSelectedIndex() == 1)
            txtResultados.setText(txtSoma1.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtEstoqueCentral.getText());
                b = Integer.parseInt(txtSoma1.getText());
            } catch (Exception e) {
            }
            txtResultados.setText(Integer.toString((a+b)));
        }
    }//GEN-LAST:event_slctSomaActionPerformed

    private void slctSoma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctSoma1ActionPerformed
        if (slctSoma1.getSelectedIndex() == 1)
            txtResultados1.setText(txtSoma2.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtVerbo.getText());
                b = Integer.parseInt(txtSoma2.getText());
            } catch (Exception e) {
            }
            txtResultados1.setText(Integer.toString((a+b)));
        }
    }//GEN-LAST:event_slctSoma1ActionPerformed

    private void slctSoma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctSoma2ActionPerformed
        if (slctSoma2.getSelectedIndex() == 1)
            txtResultados2.setText(txtSoma3.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtAldeia.getText());
                b = Integer.parseInt(txtSoma3.getText());
            } catch (Exception e) {
            }
            txtResultados2.setText(Integer.toString((a+b)));
        }
    }//GEN-LAST:event_slctSoma2ActionPerformed

    private void slctSoma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctSoma3ActionPerformed
        if (slctSoma3.getSelectedIndex() == 1)
            txtResultados3.setText(txtSoma4.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtAclimacao.getText());
                b = Integer.parseInt(txtSoma4.getText());
            } catch (Exception e) {
            }
            txtResultados3.setText(Integer.toString((a+b)));
        }
    }//GEN-LAST:event_slctSoma3ActionPerformed

    private void txtNomeUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuario5ActionPerformed

    private void txtResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadosActionPerformed

    private void txtResultados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultados1ActionPerformed

    private void txtResultados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultados2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultados2ActionPerformed

    private void txtResultados3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultados3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultados3ActionPerformed

    private void txtEstoqueCentralKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstoqueCentralKeyReleased
        
    }//GEN-LAST:event_txtEstoqueCentralKeyReleased

    private void txtSoma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoma2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoma2ActionPerformed

    private void txtSoma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoma4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoma4ActionPerformed

    private void txtSoma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoma1ActionPerformed

    private void txtSoma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoma3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoma3ActionPerformed

    private void txtSoma3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoma3KeyReleased
        if (slctSoma2.getSelectedIndex() == 1)
            txtResultados2.setText(txtSoma3.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtAldeia.getText());
                b = Integer.parseInt(txtSoma3.getText());
            } catch (Exception e) {
            }
            txtResultados2.setText(Integer.toString((a+b)));
        }
    }//GEN-LAST:event_txtSoma3KeyReleased

    private void txtSoma2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoma2KeyReleased
        if (slctSoma1.getSelectedIndex() == 1)
            txtResultados1.setText(txtSoma2.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtVerbo.getText());
                b = Integer.parseInt(txtSoma2.getText());
            } catch (Exception e) {
            }
            txtResultados1.setText(Integer.toString((a+b)));
        }
    }//GEN-LAST:event_txtSoma2KeyReleased

    private void txtSoma1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoma1KeyReleased
        if (slctSoma.getSelectedIndex() == 1)
            txtResultados.setText(txtSoma1.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtEstoqueCentral.getText());
                b = Integer.parseInt(txtSoma1.getText());
            } catch (Exception e) {
            }
            txtResultados.setText(Integer.toString((a+b)));
        }
    }//GEN-LAST:event_txtSoma1KeyReleased

    private void txtSoma4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoma4KeyReleased
        if (slctSoma3.getSelectedIndex() == 1)
            txtResultados3.setText(txtSoma4.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtAclimacao.getText());
                b = Integer.parseInt(txtSoma4.getText());
            } catch (Exception e) {
            }
            txtResultados3.setText(Integer.toString((a+b)));
        }
    }//GEN-LAST:event_txtSoma4KeyReleased

    private void txtItaimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItaimActionPerformed
        
    }//GEN-LAST:event_txtItaimActionPerformed

    private void slctSoma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctSoma4ActionPerformed
        if (slctSoma4.getSelectedIndex() == 1)
            txtResultados4.setText(txtSoma5.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtItaim.getText());
                b = Integer.parseInt(txtSoma5.getText());
            } catch (Exception e) {
            }
            txtResultados4.setText(Integer.toString((a+b)));
        } 
    }//GEN-LAST:event_slctSoma4ActionPerformed

    private void txtSoma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoma5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoma5ActionPerformed

    private void txtSoma5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoma5KeyReleased
        if (slctSoma4.getSelectedIndex() == 1)
            txtResultados4.setText(txtSoma5.getText());
        else {
            int a = 0;
            int b = 0;
            try {
                a = Integer.parseInt(txtItaim.getText());
                b = Integer.parseInt(txtSoma5.getText());
            } catch (Exception e) {
            }
            txtResultados4.setText(Integer.toString((a+b)));
        }       
    }//GEN-LAST:event_txtSoma5KeyReleased

    private void txtResultados4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultados4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultados4ActionPerformed

    private void btnAdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaActionPerformed
        altera();
    }//GEN-LAST:event_btnAdicionaActionPerformed

    private void pesquisar_cliente(){
        String sql;
        sql = "select Descricao, Tamanho, Estoque_Central, Estoque_Aldeia, Estoque_Itaim, Estoque_Verbo, Estoque_Aclimacao from tbprodutos where Descricao like ?";
        try {
            pst = conexao.prepareStatement(sql);
            // Passa conteudo da pesquisa para o ?
            // Atenção para o "%" - necessário para fazer a busca dinamica -> não incluido no string
            pst.setString(1,"%" + txtPesquisaUsuario.getText() + "%");
            rs=pst.executeQuery();
            // Usaremos a biblioteca p/ preencher a tabela
            jTabela.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    
    public void setar_campos(){
           int setar = jTabela.getSelectedRow();
           txtDescricao.setText(jTabela.getModel().getValueAt(setar, 0).toString() + " TAM " + jTabela.getModel().getValueAt(setar, 1).toString());
           txtEstoqueCentral.setText(jTabela.getModel().getValueAt(setar, 2).toString());
           txtAldeia.setText(jTabela.getModel().getValueAt(setar, 3).toString());
           txtVerbo.setText(jTabela.getModel().getValueAt(setar, 4).toString());
           txtAclimacao.setText(jTabela.getModel().getValueAt(setar, 5).toString());
           txtItaim.setText(jTabela.getModel().getValueAt(setar, 6).toString());
           guarda[0] = jTabela.getModel().getValueAt(setar, 0).toString();
           guarda[1] = jTabela.getModel().getValueAt(setar, 1).toString();
           txtResultados.setText(txtEstoqueCentral.getText());
           txtResultados1.setText(txtVerbo.getText());
           txtResultados2.setText(txtAldeia.getText());
           txtResultados3.setText(txtAclimacao.getText());
           txtResultados4.setText(txtItaim.getText());
           
       }
    
    public void altera(){
        String sql = "update tbprodutos set Estoque_Central = ?, Estoque_Aldeia = ?, Estoque_Itaim = ?, Estoque_Verbo = ?, Estoque_Aclimacao = ? where Descricao=? and Tamanho=?";
        try {
            pst=conexao.prepareStatement(sql);
            pst.setString(1, txtResultados.getText());
            pst.setString(2, txtResultados1.getText());
            pst.setString(3, txtResultados2.getText());
            pst.setString(4, txtResultados3.getText());
            pst.setString(5, txtResultados4.getText());
            pst.setString(6, guarda[0]);
            pst.setString(7, guarda[1]);
            int aux = pst.executeUpdate();
            if (aux > 0){
                JOptionPane.showMessageDialog(null, "Usuário alterado com sucesso");
                txtDescricao.setText(null);
                txtAclimacao.setText(null);
                txtAldeia.setText(null);
                txtVerbo.setText(null);
                txtItaim.setText(null);
                txtEstoqueCentral.setText(null);
                txtResultados.setText(null);
                txtResultados1.setText(null);
                txtResultados2.setText(null);
                txtResultados3.setText(null);
                txtResultados4.setText(null);
                txtPesquisaUsuario.setText(null);
                pesquisar_cliente();
                }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdiciona;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    public javax.swing.JComboBox<String> slctSoma;
    public javax.swing.JComboBox<String> slctSoma1;
    public javax.swing.JComboBox<String> slctSoma2;
    public javax.swing.JComboBox<String> slctSoma3;
    public javax.swing.JComboBox<String> slctSoma4;
    public javax.swing.JTextField txtAclimacao;
    public javax.swing.JTextField txtAldeia;
    public javax.swing.JTextField txtDescricao;
    public javax.swing.JTextField txtEstoqueCentral;
    public javax.swing.JTextField txtItaim;
    public javax.swing.JTextField txtNomeUsuario5;
    private javax.swing.JTextField txtPesquisaUsuario;
    public javax.swing.JTextField txtResultados;
    public javax.swing.JTextField txtResultados1;
    public javax.swing.JTextField txtResultados2;
    public javax.swing.JTextField txtResultados3;
    public javax.swing.JTextField txtResultados4;
    public javax.swing.JTextField txtSoma1;
    public javax.swing.JTextField txtSoma2;
    public javax.swing.JTextField txtSoma3;
    public javax.swing.JTextField txtSoma4;
    public javax.swing.JTextField txtSoma5;
    public javax.swing.JTextField txtVerbo;
    // End of variables declaration//GEN-END:variables
}
