/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pdstore.tela;

import java.sql.*;
import br.com.pdstore.dal.Conexao;
import java.awt.Color;
// Para usar a bibliote da tabela: r2xml
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Michel
 */
public class TelaPagamento extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null; 
    String pagamento = null;
    String venda;
    Calendar data = Calendar.getInstance();
    String preco;
    float recebeu = 0;
    float faltaReceber;
    float troco = 0;
    TelaVenda telavenda;
    public String vendedor;
    int unidade;
    
    float caixa_cheque;
    float caixa_dinheiro;
    
    float adicionado_cheque=0;
    float adicionado_dinheiro=0;

    public TelaPagamento(TelaVenda telavenda, String preco, String vendedor, int unidade) {
        this.unidade = unidade;
        this.vendedor = vendedor;
        this.telavenda = telavenda;
        this.preco = preco;
        faltaReceber = Float.parseFloat(preco);
        initComponents();
        lblPreco.setText("R$ " + this.preco);
        lblFaltaReceber.setText("R$ " + this.preco);
        conexao = Conexao.conector();
        calDia.setVisible(false);
        slctTipoCheque.setVisible(false);
        lblSoEmCheque.setVisible(false);
        
        le_dados();
    }

    private TelaPagamento() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        altDebito = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        altDinheiro = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        altCredito = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        altCheque = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        calDia = new com.toedter.calendar.JDateChooser();
        lblSoEmCheque = new javax.swing.JLabel();
        slctTipoCheque = new javax.swing.JComboBox<>();
        txtAdicionaPagamento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
        lblRecebido = new javax.swing.JLabel();
        lblSoEmCheque1 = new javax.swing.JLabel();
        lblFaltaReceber = new javax.swing.JLabel();
        lblSoEmCheque2 = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();
        lblSoEmCheque3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setText(" Selecione a forma de pagamento :");

        altDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Debito.png"))); // NOI18N
        altDebito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        altDebito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        altDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altDebitoActionPerformed(evt);
            }
        });

        jLabel2.setText("Dinheiro");

        altDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Dinheiro.png"))); // NOI18N
        altDinheiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        altDinheiro.setMaximumSize(new java.awt.Dimension(138, 116));
        altDinheiro.setMinimumSize(new java.awt.Dimension(138, 116));
        altDinheiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        altDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altDinheiroActionPerformed(evt);
            }
        });

        jLabel3.setText("Débito");

        altCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Credito.png"))); // NOI18N
        altCredito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        altCredito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        altCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altCreditoActionPerformed(evt);
            }
        });

        jLabel4.setText("Crédito");

        altCheque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Cheque.png"))); // NOI18N
        altCheque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        altCheque.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        altCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altChequeActionPerformed(evt);
            }
        });

        jLabel5.setText("Cheque");

        lblPreco.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(51, 153, 0));
        lblPreco.setText("R$ 00,00");
        lblPreco.setFocusTraversalPolicyProvider(true);
        lblPreco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Adicionar Pagamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblSoEmCheque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSoEmCheque.setText("*(Preencher só para cheques)");

        slctTipoCheque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        slctTipoCheque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "À vista", "Pré-datado 2x", "Pré-datado 3x" }));
        slctTipoCheque.setToolTipText("");

        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVenda);

        lblRecebido.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblRecebido.setForeground(java.awt.Color.red);
        lblRecebido.setText("R$ 00,00");
        lblRecebido.setFocusTraversalPolicyProvider(true);
        lblRecebido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSoEmCheque1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSoEmCheque1.setText("Recebido:");

        lblFaltaReceber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblFaltaReceber.setForeground(new java.awt.Color(0, 153, 0));
        lblFaltaReceber.setText("R$ 00,00");
        lblFaltaReceber.setFocusTraversalPolicyProvider(true);
        lblFaltaReceber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSoEmCheque2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSoEmCheque2.setText("Falta receber:");

        lblTroco.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTroco.setForeground(new java.awt.Color(0, 153, 0));
        lblTroco.setText("R$ 00,00");
        lblTroco.setFocusTraversalPolicyProvider(true);
        lblTroco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSoEmCheque3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSoEmCheque3.setText("Troco:");

        jButton2.setText("Limpar tudo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Cofre.png"))); // NOI18N
        jButton3.setText("Finalizar a venda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dá desconto");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Desconto.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Imprimir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Exclui_Venda.png"))); // NOI18N
        jButton6.setText(" Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(175, 175, 175)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(209, 209, 209)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(altCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(99, 99, 99)
                        .addComponent(altCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(calDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(117, 117, 117)
                .addComponent(slctTipoCheque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(lblSoEmCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(altDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(95, 95, 95)
                        .addComponent(altDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(510, 510, 510))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(67, 67, 67)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(153, 153, 153)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(281, 281, 281)
                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtAdicionaPagamento)
                                                .addGap(32, 32, 32)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addGap(145, 145, 145)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSoEmCheque2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblSoEmCheque3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(55, 55, 55))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(lblSoEmCheque1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(20, 20, 20)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFaltaReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(49, 49, 49))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(83, 83, 83)))
                        .addGap(44, 44, 44))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(altDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(altCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(altDebito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblSoEmCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(slctTipoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(calDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblSoEmCheque1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAdicionaPagamento)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblRecebido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFaltaReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblSoEmCheque2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblSoEmCheque3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblTroco)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void altDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altDebitoActionPerformed
        altCheque.setSelected(false);
        altCredito.setSelected(false);
        altDinheiro.setSelected(false);
        calDia.setVisible(false);
        slctTipoCheque.setVisible(false);
        lblSoEmCheque.setVisible(false);
    }//GEN-LAST:event_altDebitoActionPerformed

    private void altDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altDinheiroActionPerformed
        altDebito.setSelected(false);
        altCredito.setSelected(false);
        altCheque.setSelected(false);
        calDia.setVisible(false);
        slctTipoCheque.setVisible(false);
        lblSoEmCheque.setVisible(false);
    }//GEN-LAST:event_altDinheiroActionPerformed

    private void altCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altCreditoActionPerformed
        altDebito.setSelected(false);
        altDinheiro.setSelected(false);
        altCheque.setSelected(false);
        calDia.setVisible(false);
        slctTipoCheque.setVisible(false);
        lblSoEmCheque.setVisible(false);
    }//GEN-LAST:event_altCreditoActionPerformed

    private void altChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altChequeActionPerformed
        altDebito.setSelected(false);
        altCredito.setSelected(false);
        altDinheiro.setSelected(false);
        calDia.setVisible(true);
        slctTipoCheque.setVisible(true);
        lblSoEmCheque.setVisible(true);

    }//GEN-LAST:event_altChequeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // O objetivo é só chamar adiciona_pagamento se a for convertível para float
            float teste = Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", "."));
            adiciona_pagamento();
            setar_tabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite um valor válido (E não nulo). Verifique se selecionou forma de pagamento");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpa_tudo();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Float.parseFloat(this.preco) > this.recebeu) {
            JOptionPane.showMessageDialog(null, "O valor da compra ainda não foi pago integralmente! \nLembre-se de adicionar os pagamentos");
        } else {
            this.telavenda.finaliza_venda(this.preco);
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TelaDesconto telaDesconto = new TelaDesconto(this);
        telaDesconto.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            HashMap filtro = new HashMap();
            filtro.put("IdVenda", Integer.parseInt(venda));
            JasperPrint print = JasperFillManager.fillReport(getClass().getResourceAsStream("/br/com/pdstore/relatorio/CupomPueri.jasper"), filtro, conexao);
            JasperViewer.viewReport(print, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        limpa_tudo();
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void adiciona_pagamento() {
        if (altDinheiro.isSelected()) {
            this.pagamento = "Dinheiro";
        }
        if (altDebito.isSelected()) {
            this.pagamento = "Debito";
        }
        if (altCredito.isSelected()) {
            this.pagamento = "Credito";
        }
        if (altCheque.isSelected()) {
            this.pagamento = "Cheque";
        }
        String a;
        String b;
        String c;
        String d;
        String sql = "insert into tbformapagamento (IdVenda, Forma_Pagamento, Dinheiro, Dia) values (?,?,?,?)";
        float precoVenda = Float.parseFloat(this.preco.replaceAll(",", "."));
        this.recebeu += Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", "."));
        faltaReceber = precoVenda - recebeu;
        if (faltaReceber <= 0) {
            troco = -faltaReceber;
            faltaReceber = 0;
            lblRecebido.setForeground(lblPreco.getForeground());
        }
        lblRecebido.setText("R$ " + Float.toString(recebeu));
        lblFaltaReceber.setText("R$ " + Float.toString(faltaReceber));
        lblTroco.setText("R$ " + Float.toString(troco));
        if (pagamento.equalsIgnoreCase("Cheque")) {
            a = Integer.toString(calDia.getCalendar().get(Calendar.DATE));
            b = veMes(calDia.getCalendar().get(Calendar.MONTH));
            c = Integer.toString(calDia.getCalendar().get(Calendar.YEAR));
            if (slctTipoCheque.getSelectedIndex() == 0) {
                try {
                    pst = conexao.prepareStatement(sql);
                    pst.setString(1, this.venda);
                    pst.setString(2, this.pagamento);
                    if (Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) > faltaReceber) {
                        pst.setString(3, Float.toString(Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) - troco));
                    } else {
                        pst.setString(3, txtAdicionaPagamento.getText().replaceAll(",", "."));
                    }
                    d = a + "/" + b + "/" + c;
                    pst.setString(4, d);
                    if (Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) - troco>0)
                        pst.executeUpdate();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else if (slctTipoCheque.getSelectedIndex() == 1 || slctTipoCheque.getSelectedIndex() == 2) {
                for (int i = 0; i < slctTipoCheque.getSelectedIndex() + 1; i++) {
                    sql = "insert into tbformapagamento (IdVenda, Forma_Pagamento, Dinheiro, Dia) values (?,?,?,?)";
                    b = veMes(calDia.getCalendar().get(Calendar.MONTH) + i);
                    try {
                        pst = conexao.prepareStatement(sql);
                        pst.setString(1, this.venda);
                        pst.setString(2, this.pagamento);
                        pst.setString(3, Float.toString(Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) / (slctTipoCheque.getSelectedIndex() + 1)));
                        d = a + "/" + b + "/" + c;
                        pst.setString(4, d);
                        pst.executeUpdate();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                }

            }

        } else {
            a = Integer.toString(data.get(Calendar.DATE));
            b = veMes(data.get(Calendar.MONTH));
            c = Integer.toString(data.get(Calendar.YEAR));
            try {
                pst = conexao.prepareStatement(sql);
                pst.setString(1, this.venda);
                pst.setString(2, this.pagamento);
                if ((Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) > faltaReceber)) {
                    pst.setString(3, Float.toString(Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) - troco));
                } else {
                    pst.setString(3, txtAdicionaPagamento.getText().replaceAll(",", "."));
                }
                d = a + "/" + b + "/" + c;
                pst.setString(4, d);
                if (Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) - troco>0)
                    pst.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
        // Atualiza caixa -> sendo cheque
        if (pagamento.equalsIgnoreCase("Cheque")) {
            try {
                float mais;
                if (Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) > faltaReceber) {
                        mais = Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) - troco;
                    } else {
                        mais = Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", "."));
                    }
                this.adicionado_cheque += mais;
                sql = "update tbcaixa set Cheque =" + Float.toString(this.caixa_cheque + this.adicionado_cheque) + " where Id = " + this.unidade;
                pst.executeUpdate(sql);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
            
            if (pagamento.equalsIgnoreCase("Dinheiro")) {
                
                try {
                    float mais;
                    if (Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) > faltaReceber) {
                            mais = Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", ".")) - troco;
                        } else {
                            mais = Float.parseFloat(txtAdicionaPagamento.getText().replaceAll(",", "."));
                        }
                    this.adicionado_dinheiro += mais;
                    sql = "update tbcaixa set Dinheiro =" + Float.toString(this.caixa_dinheiro + this.adicionado_dinheiro) + " where Id = " + this.unidade;
                    pst.executeUpdate(sql);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            
            
        }
        

    }

    // Calendar.MONTH retorna 0 pra JAN, 1 pra FEV, etc. A seguir fazemos retonar 01 p JAN, 02 p FEV, etc
    private String veMes(int mes) {
        String b = "00";
        switch (mes) {
            case 0:
                b = "01";
                break;
            case 1:
                b = "02";
                break;
            case 2:
                b = "03";
                break;
            case 3:
                b = "04";
                break;
            case 4:
                b = "05";
                break;
            case 5:
                b = "06";
                break;
            case 6:
                b = "07";
                break;
            case 7:
                b = "08";
                break;
            case 8:
                b = "09";
                break;
            case 9:
                b = "10";
                break;
            case 10:
                b = "11";
                break;
            case 11:
                b = "12";
                break;
            case 12:
                b = "01";
                break;
            case 13:
                b = "02";
        }
        return b;
    }

    private void setar_tabela() {
        String sql = "select Forma_Pagamento as Pagamento, Dinheiro as Pago, Dia from tbformapagamento WHERE IdVenda = " + this.venda;
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            tblVenda.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    public void da_desconto(String valor) {
        this.preco = valor;
        this.faltaReceber = Float.parseFloat(valor);
        this.lblPreco.setText("R$ " + valor);
        this.lblFaltaReceber.setText("R$ " + valor);
    }

    public String get_preco() {
        return this.preco;
    }
    
    private String adicionaUnidade(int unidade){
        switch(unidade) {
            case 0:
                return "Verbo Divino";
            case 1:
                return "Aldeia da Serra";
            case 2: 
                return "Aclimação";
            case 3:
                return "Itaim";
            default:
                return "Verbo Divino";
        }
    }
    
    private void le_dados() {
        try{
            String sql = "SELECT Dinheiro, Cheque FROM tbcaixa WHERE Id = " + this.unidade;
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            rs.first();
            this.caixa_dinheiro = rs.getFloat(1);
            this.caixa_cheque = rs.getFloat(2);
        } catch (Exception e){
            
        }
    }
    
    public void limpa_tudo() {
        this.recebeu = 0;
        lblRecebido.setText("R$ 00,00");
        lblRecebido.setForeground(Color.red);
        lblFaltaReceber.setText("R$ " + this.preco);
        lblTroco.setText("R$ 00,00");
        String sql = "delete from tbformapagamento where Idvenda = " + this.venda;
        try {
            pst = conexao.prepareStatement(sql);
            pst.executeUpdate();
            setar_tabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        try {
            sql = "update tbcaixa set Dinheiro = " + this.caixa_dinheiro + ", Cheque = " + this.caixa_cheque + " where Id = " + this.unidade;
            pst = conexao.prepareStatement(sql);
            pst.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton altCheque;
    private javax.swing.JToggleButton altCredito;
    private javax.swing.JToggleButton altDebito;
    private javax.swing.JToggleButton altDinheiro;
    private com.toedter.calendar.JDateChooser calDia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblFaltaReceber;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblRecebido;
    private javax.swing.JLabel lblSoEmCheque;
    private javax.swing.JLabel lblSoEmCheque1;
    private javax.swing.JLabel lblSoEmCheque2;
    private javax.swing.JLabel lblSoEmCheque3;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JComboBox<String> slctTipoCheque;
    private javax.swing.JTable tblVenda;
    private javax.swing.JTextField txtAdicionaPagamento;
    // End of variables declaration//GEN-END:variables

    
}
