/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pdstore.tela;

import br.com.pdstore.dal.Conexao;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author miche
 */
public class TelaTransfereEstoque extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public int unidade;
    private boolean abriuVenda = false;
    private String venda = null;
    public String vendedor;

    /**
     * Creates new form TelaTransfereEstoque
     */
    public TelaTransfereEstoque(String vendedor,int unidade) {
        this.vendedor = vendedor;
        this.unidade = unidade;
        conexao = Conexao.conector();
        this.setLayout(new GridBagLayout());
        initComponents();
        atualiza_caixa();
        lblUnidade.setText(adicionaUnidade(unidade));
        cVendedor.setSelectedItem(vendedor);
        
        // Vai
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) (screenSize.getWidth() * 0.6); 
        int height = (int) screenSize.getHeight();
        this.setSize(width-50, height-150);
        this.setLocationRelativeTo(null);
    }

    private TelaTransfereEstoque() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQnt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        slctTamanho = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoDel = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
        btnDel = new javax.swing.JButton();
        btnDel2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cVendedor = new javax.swing.JComboBox<>();
        lblUnidade = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        slctUnidade = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnFinaliza = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Transferência de estoque");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        txtProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdutoKeyReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Lupa.png"))); // NOI18N

        tblProdutos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descrição", "Tamanho", "Preco", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProdutos);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Codigo");

        txtCodigo.setEditable(false);
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Qnt");

        txtQnt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQnt.setText("1");
        txtQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntActionPerformed(evt);
            }
        });

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("TAM");

        slctTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ST", "00", "02", "04", "06", "08", "10", "12", "14", "PP", "P", "M", "G", "GG", "ESP" }));
        slctTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctTamanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slctTamanho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCodigo)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(slctTamanho))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Codigo");

        txtCodigoDel.setEditable(false);
        txtCodigoDel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCodigoDel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoDel.setPreferredSize(new java.awt.Dimension(50, 50));
        txtCodigoDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoDelActionPerformed(evt);
            }
        });

        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVendaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblVenda);

        btnDel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDel.setText("Apagar");
        btnDel.setPreferredSize(new java.awt.Dimension(50, 50));
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnDel2.setText("Deletar");
        btnDel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnDel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoDel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDel2))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Vendedor: ");

        cVendedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cVendedorActionPerformed(evt);
            }
        });

        lblUnidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblUnidade.setText("jLabel8");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Arrow.png"))); // NOI18N

        slctUnidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        slctUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verbo Divino", "Aldeia da Serra", "Aclimação", "Itaim" }));
        slctUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctUnidadeActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Add_Carrinho.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Exclui_Venda.png"))); // NOI18N
        jButton6.setText("Cancelar Transicao");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnFinaliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/repeat.png"))); // NOI18N
        btnFinaliza.setText(" Finalizar");
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addGap(369, 369, 369)
                .addComponent(btnFinaliza, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addGap(380, 380, 380))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(64, 64, 64)
                        .addComponent(slctUnidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(184, 184, 184)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1)
                        .addGap(629, 629, 629))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slctUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUnidade)
                                .addComponent(cVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel8))))
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void txtProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyReleased
        pesquisar(unidade);
    }//GEN-LAST:event_txtProdutoKeyReleased

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        setar_campos(2);
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQntActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        venda = adicionar_estoque(abriuVenda);
        preenche_tabela_estoque(venda);
        slctUnidade.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int a = Integer.parseInt(txtQnt.getText());
        if (a>1)
            a--;
        txtQnt.setText(Integer.toString(a));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int a = Integer.parseInt(txtQnt.getText());
        a++;
        txtQnt.setText(Integer.toString(a));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void slctTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctTamanhoActionPerformed
        pesquisar(unidade);
    }//GEN-LAST:event_slctTamanhoActionPerformed

    private void cVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cVendedorActionPerformed

    }//GEN-LAST:event_cVendedorActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(venda != null)
            cancela_venda(venda);
        else
            this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void slctUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctUnidadeActionPerformed
        pesquisar(this.unidade);
    }//GEN-LAST:event_slctUnidadeActionPerformed

    private void txtCodigoDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoDelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoDelActionPerformed

    private void tblVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVendaMouseClicked
        try {
            int setar = tblVenda.getSelectedRow();
            txtCodigoDel.setText(tblVenda.getModel().getValueAt(setar, 0).toString());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tblVendaMouseClicked

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed

    }//GEN-LAST:event_btnDelActionPerformed

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed
        if (this.venda != null) {
            JOptionPane.showMessageDialog(null, "Transação realizada com sucesso!");
            this.dispose();
            try {
                conexao.close();
            } catch (Exception e) {
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Faça uma transação!");
        }
    }//GEN-LAST:event_btnFinalizaActionPerformed

    private void btnDel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel2ActionPerformed
        deleta_item(txtCodigoDel.getText());
        preenche_tabela_estoque(venda);
    }//GEN-LAST:event_btnDel2ActionPerformed
    
    private void pesquisar(int unidade){
        String sql = "select Codigo, Descricao, Tamanho, " + qualEstoque(unidade) + "," + qualEstoque(slctUnidade.getSelectedIndex()) +  " from tbprodutos where Descricao like ? and Tamanho like ?";
            
        try {
            pst = conexao.prepareStatement(sql);
            // Passa conteudo da pesquisa para o ?
            // Atenção para o "%" - necessário para fazer a busca dinamica -> não incluido no string
            if (slctTamanho.getSelectedItem().toString().equalsIgnoreCase(" ")){
                pst.setString(1, "%" + txtProduto.getText() + "%");
                pst.setString(2, "%%");
            }
            else{
                pst.setString(1, "%" + txtProduto.getText() + "%");
                pst.setString(2, "%" + slctTamanho.getSelectedItem().toString() + "%");            
            }
            rs=pst.executeQuery();
            // Usaremos a biblioteca p/ preencher a tabela
            tblProdutos.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void setar_campos(int opcao){
        int setar;
        try {
            setar = tblProdutos.getSelectedRow();
            txtCodigo.setText(tblProdutos.getModel().getValueAt(setar, 0).toString());
            txtProduto.setText(tblProdutos.getModel().getValueAt(setar, 1).toString());
            slctTamanho.setSelectedItem(tblProdutos.getModel().getValueAt(setar, 2).toString());

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }
    
    private String adicionar_estoque(boolean abriu){
        int a;
        String aux = "";
        try {
            if (!abriu) {
                String sql = "insert into tbtransicao_estoque(De, Para, IdVendedor) values (?,?,?)";
                pst = conexao.prepareStatement(sql);
                pst.setString(1, adicionaUnidade(unidade));
                pst.setString(2, (String) slctUnidade.getSelectedItem());
                pst.setString(3, (String) cVendedor.getSelectedItem());
                pst.executeUpdate();
            }
            this.abriuVenda = true;
            // Para pegar o valor de Id da venda.
            pst = conexao.prepareStatement("select IdTrans from tbtransicao_estoque order by IdTrans desc");
            rs = pst.executeQuery("select IdTrans from tbtransicao_estoque order by IdTrans desc");
            // Para pegar o último adicionado
            rs.first();
            aux = rs.getString(1);
            String sql = "insert into tbitens_estoque(IdTrans, Quantidade, Idproduto) values (?,?,?)";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            pst.setString(2, txtQnt.getText());
            pst.setString(3, txtCodigo.getText());
            a = pst.executeUpdate();
            
            // Para dar baixa no estoque que transferiu.
            sql = "SELECT " + qualEstoque(this.unidade) + " FROM tbitens_estoque AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbtransicao_estoque AS Estoque ON Itens.IdTrans = Estoque.IdTrans WHERE Produto.Codigo = "+txtCodigo.getText() +" and Estoque.IdTrans = " + aux;
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            rs.next();
            int estoque = Integer.parseInt(rs.getString(1));
            estoque = estoque - Integer.parseInt(txtQnt.getText());
            sql = "update tbprodutos set " + qualEstoque(this.unidade) + "= " + Integer.toString(estoque) + " where Codigo = " + txtCodigo.getText();
            pst = conexao.prepareStatement(sql);
            pst.executeUpdate();

            // Para dar alta no estoque que recebeu.
            sql = "SELECT " + qualEstoque(slctUnidade.getSelectedIndex()) + " FROM tbitens_estoque AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbtransicao_estoque AS Estoque ON Itens.IdTrans = Estoque.IdTrans WHERE Produto.Codigo = " + txtCodigo.getText() +" and Estoque.IdTrans = " + aux;
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            rs.next();
            estoque = Integer.parseInt(rs.getString(1));
            estoque = estoque + Integer.parseInt(txtQnt.getText());
            sql = "update tbprodutos set " + qualEstoque(slctUnidade.getSelectedIndex()) + " = " + Integer.toString(estoque) + " where Codigo = " + txtCodigo.getText();
            pst = conexao.prepareStatement(sql);
            pst.executeUpdate();
            // Terminamos as operações necessárias
            
            txtQnt.setText("1");
            slctTamanho.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Até aqui foi");
            preenche_tabela_estoque(this.venda);
            
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        return aux;
    }
    
    private void preenche_tabela_estoque(String aux){
        try {
            String sql = "select Itens.IdProduto, Produto.Descricao, Produto.Tamanho, Itens.Quantidade from tbitens_estoque as Itens join tbprodutos as Produto on Itens.Idproduto = Produto.Codigo join tbtransicao_estoque as Estoque on Itens.IdTrans = Estoque.IdTrans where Estoque.IdTrans = ?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            rs=pst.executeQuery();
            tblVenda.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    private void cancela_venda(String aux) {
        repoe_estoque();
        try {
            // Deleta tabela de itens vendidos
            String sql = "delete from tbitens_estoque where IdTrans=?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            pst.execute();
            // Deleta da tabela Venda
            sql = "delete from tbtransicao_estoque where IdTrans=?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Transição excluída com sucesso");
            this.dispose();
            /*
            txtCliente.setText(null);
            txtPreco.setText(null);
            txtProduto.setText(null);
            txtId.setText(null);
            slctTamanho.setSelectedIndex(0);*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            this.dispose();
        }

    }
    
    private void repoe_estoque(){
        // Declaração de variáveis
        String aux = this.venda;
        // Coloca de volta no que transferiu.
        String sql = "SELECT Itens.Quantidade," + qualEstoque(unidade) + ", Produto.Codigo FROM tbitens_estoque AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbtransicao_estoque AS Estoque ON Itens.IdTrans = Estoque.IdTrans WHERE Produto.Codigo = "+txtCodigo.getText() +" and Estoque.IdTrans = " + aux;
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            rs.first();
            do {                
                int quantidade = rs.getInt(1);
                int estoque = rs.getInt(2); 
                int soma = quantidade + estoque;
                sql = "update tbprodutos set " + qualEstoque(unidade) + " = " + Integer.toString(soma) + " where Codigo = " + rs.getInt(3);
                pst = conexao.prepareStatement(sql);
                pst.executeUpdate();
            } while (rs.next());
        
        // Tira de onde foi transferido. 
        sql = "SELECT Itens.Quantidade," + qualEstoque(slctUnidade.getSelectedIndex()) + ", Produto.Codigo FROM tbitens_estoque AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbtransicao_estoque AS Estoque ON Itens.IdTrans = Estoque.IdTrans WHERE Produto.Codigo = "+txtCodigo.getText() +" and Estoque.IdTrans = " + aux;
        pst = conexao.prepareStatement(sql);
        rs = pst.executeQuery(sql);
        rs.first();
        do {                
            int quantidade = rs.getInt(1);
            int estoque = rs.getInt(2); 
            int soma = quantidade - estoque;
            sql = "update tbprodutos set " + qualEstoque(slctUnidade.getSelectedIndex()) + " = " + Integer.toString(soma) + " where Codigo = " + rs.getInt(3);
            pst = conexao.prepareStatement(sql);
            pst.executeUpdate();
        } while (rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
    }
    
    private String adicionaUnidade(int unidade){
        switch(unidade) {
            case 0:
                return "Verbo Divino";
            case 1:
                return "Aldeia da Serra";
            case 2: 
                return "Aclimação";
            case 3:
                return "Itaim";
            default:
                return "Erro";
        }
    }
    
    private String qualEstoque(int unidade) {
        switch(unidade) {
            case 0:
                return "Estoque_Verbo";
            case 1:
                return "Estoque_Aldeia";
            case 2: 
                return "Estoque_Aclimacao";
            case 3:
                return "Estoque_Itaim";
            default:
                return "Estoque_Verbo";
        }
    }
    
    private void atualiza_caixa() {
        String sql = "SELECT usuario FROM tblogin";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            rs.first();
            do {                
                this.cVendedor.addItem(rs.getString(1));
            } while (rs.next());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } 
    } // Essa função é só para mudar a slctBOX c os valores dos vendedores.
    
    private void deleta_item(String item) {
        String sql = "DELETE FROM tbitens_estoque WHERE IdProduto = " + item;
        try{
            pst.execute(sql);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTransfereEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTransfereEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTransfereEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTransfereEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTransfereEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDel2;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JComboBox<String> cVendedor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblUnidade;
    private javax.swing.JComboBox<String> slctTamanho;
    private javax.swing.JComboBox<String> slctUnidade;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTable tblVenda;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoDel;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQnt;
    // End of variables declaration//GEN-END:variables
}
