/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pdstore.tela;
import java.sql.*;
import br.com.pdstore.dal.Conexao;
import java.awt.Color;
// Para usar a bibliote da tabela: r2xml
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Michel
 */
public class TelaVenda extends javax.swing.JFrame {
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public int unidade;
    private boolean abriuVenda = false;
    private String venda = null;

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
        conexao = Conexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQnt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        slctTamanho = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVenda = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela de Vendas");
        setExtendedState(6);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        txtCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClienteKeyReleased(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Telefone", "Cpf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Add_Cliente.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id");

        txtId.setEditable(false);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setText("1");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Lupa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 552, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        txtProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdutoKeyReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Lupa.png"))); // NOI18N

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descrição", "Tamanho", "Preco", "Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProdutos);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Codigo");

        txtCodigo.setEditable(false);
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Qnt");

        txtQnt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQnt.setText("1");
        txtQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Add_Carrinho.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("TAM");

        slctTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ST", "00", "02", "04", "06", "08", "10", "12", "14", "PP", "P", "M", "G", "GG", "ESP" }));
        slctTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slctTamanhoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Preço");

        txtPreco.setEditable(false);
        txtPreco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(slctTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(slctTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4)
                                .addComponent(jButton3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        tblVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblVenda);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Total");

        lblPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPreco.setText("00.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblPreco)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblPreco))
                .addContainerGap())
        );

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Finaliza_Venda.png"))); // NOI18N
        jButton5.setText("Ir para pagamentos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdstore/imagem/Exclui_Venda.png"))); // NOI18N
        jButton6.setText("Cancelar Venda");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1290, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyReleased
        pesquisar(1, unidade);
    }//GEN-LAST:event_txtClienteKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaCadastroCliente telaCadastroCliente = new TelaCadastroCliente();
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        setar_campos(1);
    }//GEN-LAST:event_tblClienteMouseClicked

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void txtProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyReleased
        pesquisar(2, unidade);
    }//GEN-LAST:event_txtProdutoKeyReleased

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        setar_campos(2);
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQntActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int a = Integer.parseInt(txtQnt.getText());
        a++;
        txtQnt.setText(Integer.toString(a));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int a = Integer.parseInt(txtQnt.getText());
        if (a>1)
            a--;
        txtQnt.setText(Integer.toString(a));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void slctTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slctTamanhoActionPerformed
        pesquisar(2,unidade);
    }//GEN-LAST:event_slctTamanhoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        venda = adicionar_carrinho(abriuVenda);
        preenche_tabela_venda(venda);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (this.venda != null) {
            TelaPagamento telaPagamento = new TelaPagamento(this, lblPreco.getText());
            telaPagamento.venda = this.venda;
            telaPagamento.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Venda um item!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(venda != null)
            cancela_venda(venda);
        else 
            this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void pesquisar(int opcao, int unidade){
        String sql = "";
        if (opcao == 1)
            sql = "select Id, Nome, Telefone, Cpf from tbcliente where Nome like ?";
        else
            switch(unidade){
                // 0 = Verbo, 1 = Aldeia, 2 = Aclimacao, 3 = Itaim - Ver TelaQualUnidade
                case 0:
                    sql = "select Codigo, Descricao, Tamanho, Preco_Venda, Estoque_Verbo from tbprodutos where Descricao like ? and Tamanho like ?";
                    break;
                case 1:
                    sql = "select Codigo, Descricao, Tamanho, Preco_Venda, Estoque_Aldeia from tbprodutos where Descricao like ? and Tamanho like ?";
                    break;
                case 2:
                    sql = "select Codigo, Descricao, Tamanho, Preco_Venda, Estoque_Aclimacao from tbprodutos where Descricao like ? and Tamanho like ?";
                    break;
                case 3:
                    sql = "select Codigo, Descricao, Tamanho, Preco_Venda, Estoque_Itaim from tbprodutos where Descricao like ? and Tamanho like ?";
                    break;
            }
            
        try {
            pst = conexao.prepareStatement(sql);
            // Passa conteudo da pesquisa para o ?
            // Atenção para o "%" - necessário para fazer a busca dinamica -> não incluido no string
            if (opcao == 1){
                pst.setString(1, "%" + txtCliente.getText() + "%");
                rs=pst.executeQuery();
                // Usaremos a biblioteca p/ preencher a tabela
                tblCliente.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else{
                if (slctTamanho.getSelectedItem().toString().equalsIgnoreCase(" ")){
                    pst.setString(1, "%" + txtProduto.getText() + "%");
                    pst.setString(2, "%%");
                }
                else{
                    pst.setString(1, "%" + txtProduto.getText() + "%");
                    pst.setString(2, "%" + slctTamanho.getSelectedItem().toString() + "%");            
                }
                rs=pst.executeQuery();
                // Usaremos a biblioteca p/ preencher a tabela
                tblProdutos.setModel(DbUtils.resultSetToTableModel(rs));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void setar_campos(int opcao){
        int setar;
        try {
            if(opcao ==1) {
                setar = tblCliente.getSelectedRow();
                txtCliente.setText(tblCliente.getModel().getValueAt(setar, 1).toString());
                txtId.setText(tblCliente.getModel().getValueAt(setar, 0).toString());
            } else {
                setar = tblProdutos.getSelectedRow();
                txtPreco.setText(tblProdutos.getModel().getValueAt(setar, 3).toString());
                txtCodigo.setText(tblProdutos.getModel().getValueAt(setar, 0).toString());
                txtProduto.setText(tblProdutos.getModel().getValueAt(setar, 1).toString());
                slctTamanho.setSelectedItem(tblProdutos.getModel().getValueAt(setar, 2).toString());

                
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }
    
    private String adicionar_carrinho(boolean abriu){
        int a;
        String aux = "";
        try {
            if (!abriu) {
                pst = conexao.prepareStatement("insert into tbvenda(Preco) values (0)");
                pst.executeUpdate("insert into tbvenda(Preco) values (0)");
            }
            this.abriuVenda = true;
            // Para pegar o valor de Id da venda.
            pst = conexao.prepareStatement("select IdVenda from tbvenda order by IdVenda desc");
            rs = pst.executeQuery("select IdVenda from tbvenda order by IdVenda desc");
            // Para pegar o último adicionado
            rs.first();
            aux = rs.getString(1);
            String sql = "insert into tbitens_venda(Idvenda, Quantidade, Idproduto, Total) values (?,?,?,?)";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            pst.setString(2, txtQnt.getText());
            pst.setString(3, txtCodigo.getText());
            float conta = Float.parseFloat(txtQnt.getText()) * Float.parseFloat(txtPreco.getText());
            pst.setString(4, Float.toString(conta));

            a = pst.executeUpdate();
            
            // Para dar baixa no estoque
            switch(this.unidade){
                // 0 = Verbo, 1 = Aldeia, 2 = Aclimacao, 3 = Itaim - Ver TelaQualUnidade
                case 0:
                    sql = "SELECT Estoque_Verbo FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbvenda AS Venda ON Itens.IdVenda = Venda.IdVenda WHERE Produto.Codigo = "+txtCodigo.getText() +" and Venda.IdVenda = " + aux;
                    break;
                case 1:
                    sql = "SELECT Estoque_Aldeia FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbvenda AS Venda ON Itens.IdVenda = Venda.IdVenda WHERE Produto.Codigo = "+txtCodigo.getText() +" and Venda.IdVenda = " + aux;
                    break;
                case 2:
                    sql = "SELECT Estoque_Aclimacao FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbvenda AS Venda ON Itens.IdVenda = Venda.IdVenda WHERE Produto.Codigo = "+txtCodigo.getText() +" and Venda.IdVenda = " + aux;
                    break;
                case 3:
                    sql = "SELECT Estoque_Itaim FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbvenda AS Venda ON Itens.IdVenda = Venda.IdVenda WHERE Produto.Codigo = "+txtCodigo.getText() +" and Venda.IdVenda = " + aux;
                    break;
            }
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            rs.next();
            int estoque = Integer.parseInt(rs.getString(1));
            estoque = estoque - Integer.parseInt(txtQnt.getText());
            switch(this.unidade){
                // 0 = Verbo, 1 = Aldeia, 2 = Aclimacao, 3 = Itaim - Ver TelaQualUnidade
                case 0:
                    sql = "update tbprodutos set Estoque_Verbo = " + Integer.toString(estoque) + " where Codigo = " + txtCodigo.getText();
                    break;
                case 1:
                    sql = "update tbprodutos set Estoque_Aldeia = " + Integer.toString(estoque) + " where Codigo = " + txtCodigo.getText();
                    break;
                case 2:
                    sql = "update tbprodutos set Estoque_Aclimacao = " + Integer.toString(estoque) + " where Codigo = " + txtCodigo.getText();
                    break;
                case 3:
                    sql = "update tbprodutos set Estoque_Itaim = " + Integer.toString(estoque) + " where Codigo = " + txtCodigo.getText();
                    break;
            }
            
            pst = conexao.prepareStatement(sql);
            pst.executeUpdate();
            txtQnt.setText("1");
            slctTamanho.setSelectedIndex(0);
            preenche_tabela_venda(this.venda);
        } catch (Exception e){ 
            JOptionPane.showMessageDialog(null, e);
        }
        return aux;
    }
    
    private void preenche_tabela_venda(String aux){
        try {
            String sql = "select Produto.Descricao, Produto.Tamanho, Produto.Preco_Venda as Preco, Itens.Quantidade, Itens.Total from tbitens_venda as Itens join tbprodutos as Produto on Itens.Idproduto = Produto.Codigo join tbvenda as Venda on Itens.IdVenda = Venda.IdVenda where Venda.IdVenda = ?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            rs=pst.executeQuery();
            tblVenda.setModel(DbUtils.resultSetToTableModel(rs));
            sql = "select sum(Itens.Total) FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo WHERE IdVenda = ?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            rs=pst.executeQuery();
            rs.next();
            lblPreco.setText(rs.getString(1));
        } catch (Exception e) {
        }
        
    }
    
    private void cancela_venda(String aux) {
        repoe_estoque();
        try {
            // Deleta tabela de itens vendidos
            String sql = "delete from tbformapagamento where IdVenda=?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            pst.execute();
            // Deleta da tabela forma de pagamentos
            sql = "delete from tbitens_venda where IdVenda=?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            pst.execute();
            // Deleta da tabela Venda
            sql = "delete from tbvenda where IdVenda=?";
            pst = conexao.prepareStatement(sql);
            pst.setString(1, aux);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Venda excluída com sucesso");
            this.dispose();
            /*
            txtCliente.setText(null);
            txtPreco.setText(null);
            txtProduto.setText(null);
            txtId.setText(null);
            slctTamanho.setSelectedIndex(0);*/

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            this.dispose();
        }

    }
    
    public void finaliza_venda(String preco) {
        String qualUnidade = adicionaUnidade(this.unidade);
        try {
            String sql = "update tbvenda set Preco = "+ preco +", idcliente = "+ txtId.getText() + ", Unidade = '"+qualUnidade+"' where IdVenda = " + this.venda;
            pst = conexao.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Venda finalizada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        this.abriuVenda = false;
        TelaVenda telaVenda = new TelaVenda();
        telaVenda.unidade = this.unidade;
        telaVenda.setVisible(true);
        this.dispose();
        
        
}
    
    private void repoe_estoque(){
        // Declaração de variáveis
        String sql="";
        String aux = this.venda;
        switch(this.unidade){
                // 0 = Verbo, 1 = Aldeia, 2 = Aclimacao, 3 = Itaim - Ver TelaQualUnidade
                case 0:
                    sql = "SELECT Itens.Quantidade, Estoque_Verbo, Produto.Codigo FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbvenda AS Venda ON Itens.IdVenda = Venda.IdVenda WHERE Produto.Codigo = "+txtCodigo.getText() +" and Venda.IdVenda = " + aux;
                    break;
                case 1:
                    sql = "SELECT Itens.Quantidade, Estoque_Aldeia, Produto.Codigo FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbvenda AS Venda ON Itens.IdVenda = Venda.IdVenda WHERE Produto.Codigo = "+txtCodigo.getText() +" and Venda.IdVenda = " + aux;
                    break;
                case 2:
                    sql = "SELECT Itens.Quantidade, Estoque_Aclimacao, Produto.Codigo FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbvenda AS Venda ON Itens.IdVenda = Venda.IdVenda WHERE Produto.Codigo = "+txtCodigo.getText() +" and Venda.IdVenda = " + aux;
                    break;
                case 3:
                    sql = "SELECT Itens.Quantidade, Estoque_Itaim, Produto.Codigo FROM tbitens_venda AS Itens JOIN tbprodutos AS Produto ON Itens.Idproduto = Produto.Codigo JOIN tbvenda AS Venda ON Itens.IdVenda = Venda.IdVenda WHERE Produto.Codigo = "+txtCodigo.getText() +" and Venda.IdVenda = " + aux;
                    break;
            }
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            rs.first();
            do {                
                int quantidade = rs.getInt(1);
                int estoque = rs.getInt(2); 
                int soma = quantidade + estoque;
                switch(this.unidade){
                // 0 = Verbo, 1 = Aldeia, 2 = Aclimacao, 3 = Itaim - Ver TelaQualUnidade
                case 0:
                    sql = "update tbprodutos set Estoque_Verbo = " + Integer.toString(soma) + " where Codigo = " + rs.getInt(3);
                    break;
                case 1:
                    sql = "update tbprodutos set Estoque_Aldeia = " + Integer.toString(soma) + " where Codigo = " + rs.getInt(3);
                    break;
                case 2:
                    sql = "update tbprodutos set Estoque_Aclimacao = " + Integer.toString(soma) + " where Codigo = " + rs.getInt(3);
                    break;
                case 3:
                    sql = "update tbprodutos set Estoque_Itaim = " + Integer.toString(soma) + " where Codigo = " + rs.getInt(3);
                    break;
            }
                pst = conexao.prepareStatement(sql);
                pst.executeUpdate();
            } while (rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
    }
    
    private String adicionaUnidade(int unidade){
        switch(unidade) {
            case 0:
                return "Verbo Divino";
            case 1:
                return "Aldeia da Serra";
            case 2: 
                return "Aclimação";
            case 3:
                return "Itaim";
            default:
                return "Verbo Divino";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JComboBox<String> slctTamanho;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTable tblVenda;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQnt;
    // End of variables declaration//GEN-END:variables
}
